//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(CuentaPagoMetadata))]
    public partial class CuentaPago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CuentaPago()
        {
            this.Factura = new HashSet<Factura>();
            this.Usuario1 = new HashSet<Usuario>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdTipoPago { get; set; }
        public string NumCuenta { get; set; }
        public System.DateTime FechaExp { get; set; }
        public string CodSeguridad { get; set; }
    
        public string CuentaEncrp()
        {
            return "***********" + NumCuenta.Substring(NumCuenta.Length - 4);
        }

        public virtual TipoPago TipoPago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factura> Factura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuario1 { get; set; }
    }
}
