//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(FacturaMetadata))]


    public partial class Factura
    {
        public int IdFactura { get; set; }
        public Nullable<int> IdCuentaPago { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> IVA { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<int> IdOrden { get; set; }
    
        public virtual CuentaPago CuentaPago { get; set; }
        public virtual Orden Orden { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
