//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenDetalle
    {
        public int IdOrden { get; set; }
        public int idProducto { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
    
        public virtual Estado Estado1 { get; set; }
        public virtual Orden Orden { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
