//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respuesta
    {
        public int Id { get; set; }
        public Nullable<int> IdMensaje { get; set; }
        public string Respuesta1 { get; set; }
        public Nullable<int> IdProveedor { get; set; }
    
        public virtual Mensaje Mensaje { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
